# Generated by Django 6.0.5 on 2026-05-08 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='프로젝트명')),
                ('status', models.CharField(choices=[('draft', '초안 작성중'), ('agent_processing', 'AI 처리중'), ('review', '변리사 검토중'), ('done', '완료')], default='draft', max_length=20)),
                ('original_data_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_to_solve', models.TextField(verbose_name='해결하고자 하는 과제')),
                ('prior_art_problem', models.TextField(verbose_name='기존 기술의 문제점')),
                ('core_tech', models.TextField(verbose_name='핵심 기술 구성')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workspace.patentproject')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('inventor', '발명가'), ('attorney', '변리사')], default='inventor', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
