# Generated by Django 6.0.5 on 2026-05-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventioninput",
            name="expected_effect",
            field=models.TextField(blank=True, null=True, verbose_name="기대 효과"),
        ),
    ]
