# Generated by Django 6.0.5 on 2026-05-11 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0003_inventioninput_expected_effect"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="workspace.patentproject",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultingState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase", models.IntegerField(default=1)),
                ("collecting_steps", models.BooleanField(default=False)),
                (
                    "ext_problem",
                    models.TextField(
                        blank=True, null=True, verbose_name="추출된 문제점"
                    ),
                ),
                (
                    "ext_solution",
                    models.TextField(
                        blank=True, null=True, verbose_name="추출된 해결방안"
                    ),
                ),
                (
                    "ext_differentiation",
                    models.TextField(
                        blank=True, null=True, verbose_name="추출된 차별성"
                    ),
                ),
                (
                    "ext_effect",
                    models.TextField(
                        blank=True, null=True, verbose_name="추출된 기대효과"
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consulting_state",
                        to="workspace.patentproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetailElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("implementation", "구현수단"),
                            ("parameter", "데이터 파라미터"),
                            ("algorithm", "핵심로직"),
                            ("optional", "부가기능"),
                            ("error_handling", "예외처리"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="workspace.patentproject",
                    ),
                ),
            ],
        ),
    ]
