# Generated by Django 6.0.5 on 2026-05-11 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0004_chatmessage_consultingstate_detailelement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={},
        ),
        migrations.AlterField(
            model_name="detailelement",
            name="element_type",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="AlgorithmStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_seq", models.IntegerField()),
                ("content", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="algorithm_steps",
                        to="workspace.patentproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsultationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase", models.IntegerField(default=1)),
                ("collecting_steps", models.BooleanField(default=False)),
                ("ext_problem", models.TextField(blank=True, null=True)),
                ("ext_solution", models.TextField(blank=True, null=True)),
                ("ext_differentiation", models.TextField(blank=True, null=True)),
                ("ext_effect", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_state",
                        to="workspace.patentproject",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ConsultingState",
        ),
    ]
