# Generated by Django 6.0.5 on 2026-05-22 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0005_alter_chatmessage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatentClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_no", models.IntegerField(verbose_name="청구항 번호")),
                (
                    "is_dependent",
                    models.BooleanField(default=False, verbose_name="종속항 여부"),
                ),
                (
                    "cited_claim_no",
                    models.JSONField(
                        blank=True, default=list, verbose_name="인용항 번호 목록"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=50, verbose_name="카테고리(방법/시스템 등)"
                    ),
                ),
                ("content", models.TextField(verbose_name="청구항 내용")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="workspace.patentproject",
                    ),
                ),
            ],
            options={
                "ordering": ["claim_no"],
            },
        ),
    ]
