# Generated by Django 6.0.5 on 2026-06-08 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0007_patentdrawingfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriorArtReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_level", models.CharField(max_length=50)),
                ("analysis_summary", models.TextField()),
                ("full_json_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prior_art_report",
                        to="workspace.patentproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("markdown_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specification_doc",
                        to="workspace.patentproject",
                    ),
                ),
            ],
        ),
    ]
