# Generated by Django 6.0.6 on 2026-06-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_priorartreport_specificationdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentdrawingfile',
            name='image_url',
            field=models.URLField(help_text='S3에 업로드된 도면 이미지 URL', max_length=500),
        ),
    ]
